#!/usr/bin/env bash

set -x

_USER=vagrant
_NON_ROOT_USER_UID_OLD=1000
_NON_ROOT_USER_GID_OLD=1000
_NON_ROOT_USER_UID=1100
_NON_ROOT_USER_GID=1100
_PYENV_PYTHON_VERSION=3.5.2

DOCKER_COMPOSE_VERSION=1.8.0
DOCKER_VERSION=1.12.6-0~ubuntu-trusty
DOCKER_PACKAGE_NAME=docker-engine
DEBIAN_FRONTEND=noninteractive
